
export const metadata = {
  title: "TripleM | Auth",
  description: "Generated by create next app",
};

const layout = ({children}) => {
    return (
        <>
            {children}
        </>
    );
};

export default layout;